# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.network "public_network"
	config.vm.synced_folder "./", "/vagrant"
	
	config.vm.provision "chef_solo" do |chef|
		chef.cookbooks_path = ["cookbooks"]
		chef.roles_path = "roles"
		chef.add_role "e2ee-server"
	end
end
